import type { Metadata } from "next";
import "./globals.css";
import { clsx } from "clsx";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark" suppressHydrationWarning={true}>
      <body className={clsx("antialiased")}>
        <Container>
          <Header />
          {children}
        </Container>
        <Toaster />
      </body>
    </html>
  );
}
